spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    platform: h2
    url: jdbc:h2:~/tim;DB_CLOSE_ON_EXIT=TRUE
    username: sa
    password: sa
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 8080
