spring:
  h2:
    console:
      enabled: false
      path: /h2-console
  datasource:
    platform: h2
    url: jdbc:h2:~/tim-for-tests;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
  jpa:
    properties:
      hibernate:
        ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 8082
